In [1]:
#import libraries
import numpy as np
import pandas as pd

In [3]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr)
print("\nAverage number", arr.mean())

[10 20 30 40 50 60 70]

Average number 40.0


In [4]:
#indexing 
print(arr[3])
print(arr[-2])
print(arr[6])
print(arr[-4])

40
60
70
40


In [8]:
#slicing
print(arr[1:6])
print(arr[6:])
print(arr[:7])
print(arr[-6:-1])
print(arr[7:])
print(arr[-1:-6])

[20 30 40 50 60]
[70]
[10 20 30 40 50 60 70]
[20 30 40 50 60]
[]
[]


In [10]:
#30 DAYS DAILY STEPS TRACKER
np.random.seed(42) #reproducibility
days = np.arange(1, 31)
steps = np.random.randint(3456, 12034, size=30)

print("Days:", days)
print("Steps", steps)

Days: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Steps [10726  4316  8846  8647  9190  9721  3922  7882  9034 11778  5141  4225
 10405  5889  8767  8507  9876  4640  8011  6841  9852  6014 11305  5503
  6203  3645  6190  6461  8114  5355]


In [11]:
data = pd.DataFrame({
    "Days": days,
    "Steps": steps
})

data

,Days,Steps
0,1,10726
1,2,4316
2,3,8846
3,4,8647
4,5,9190
5,6,9721
6,7,3922
7,8,7882
8,9,9034
9,10,11778


In [12]:
#basic stats
mean_step = np.mean(steps)
std_step = np.std(steps) #std= standard deviation

print("Average step:", mean_step)
print("Median step:", np.median(steps))
print("Minimun step:", np.min(steps))
print("Maximum step:", np.max(steps))
print("Standard deviation step:", std_step)

Average step: 7500.2
Median step: 7946.5
Minimun step: 3645
Maximum step: 11778
Standard deviation step: 2309.770715893679


In [15]:
#goal analysis for days of over 10000 steps
goal = np.where(steps > 10000)[0] + 1
print(goal)

[ 1 10 13 23]


In [19]:
#analysis for weekly steps
weeks = np.array_split(steps, 4)
print("Week Total Analysis:")
week_total = [print(week.sum()) for week in weeks]
print("\nWeek Average Analysis:")
week_avg = [print(week.mean()) for week in weeks]

Week Total Analysis:
63250
63746
56539
41471

Week Average Analysis:
7906.25
7968.25
8077.0
5924.428571428572


In [24]:
#anomaly detection
lower_bound = mean_step - 2 * std_step
upper_bound = mean_step + 2 * std_step
print(lower_bound)
print(upper_bound)

print(round(lower_bound, 2))
print(round(upper_bound, 2))

anomaly = np.where((steps < lower_bound) | (steps > upper_bound)) [0] + 1
print("Anomaly detection (low/high):", anomaly)

2880.6585682126415
12119.741431787359
2880.66
12119.74
Anomaly detection (low/high): []
